require("./jquery.form")
require("./jquery.jedate")
require("./layer")
// require("./semantic.min")
require('./data')
require("./area")
require('./jquery.nicescroll')
require('./people')
require('./api')