module.exports = '<div class="else_box">'
+'<div class="pub_box">'
+'<div class="pub_title">'
+'<h1>变更理由</h1>'
+'</div>'
+'<div class="pub_form_box">'
+'<div class="pc_box" data-field="change_reason">'
+'<div class="pc_info">'
+'<p>变更理由:</p>'
+'</div>'
+'<div class="pc_content">'
+'<textarea cols="30" rows="10" placeholder="请填写变更理由"></textarea>'
+'</div>'
+'</div>'
+'<div class="pc_box" data-field="change_data">'
+'<div class="pc_info">'
+'<p>支撑材料:</p>'
+'</div>'
+'<div class="pc_content">'
+'<div class="preview_box">'
+'<p class="form_input">'
+'<span>未选择任何文件</span>'
+'<a href="javascript:;">期末考试齐文件_01.xls</a>'
+'</p>'
+'</div>'
+'<form action="/TM/school/student/achievement/uploadFile" method="post" class="file_box">'
+'<a target="_blank" href="javascript:;" class="file_btn">'
+'<span>上传文件</span>'
+'<input type="file" class="js_upload" name="file" data-id="">'
+'</a>'
+'</form>'
+'<p class="up_info">最大可上传2MB</p>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'<div class="pub_box">'
+'<div class="pub_title">'
+'<h1>'
+'<span class="title">申请人信息</span>'
+'</h1>'
+'</div>'
+'<div class="pub_form_box">'
+'<div class="pc_box" data-field="idcard_type">'
+'<div class="pc_info">'
+'<p>申请人证件类型:</p>'
+'</div>'
+'<div class="pc_content">'
+'<p class="dropdown" data-id=""><span>请选择</span><i></i></p>'
+'<ul class="drop_list">'
+'<li data-id="1">办学许可证</li>'
+'<li data-id="2">法人登记证</li>'
+'<li data-id="3">组织机构代码证</li>'
+'<li data-id="4">身份证</li>'
+'</ul>'
+'</div>'
+'</div>'
+'<div class="pc_box" data-field="idcard_id">'
+'<div class="pc_info">'
+'<p class="input_p">申请人证件号码:</p>'
+'</div>'
+'<div class="pc_content">'
+'<input type="text" placeholder="请填写">'
+'</div>'
+'</div>'
+'<div class="pc_box" data-field="name">'
+'<div class="pc_info">'
+'<p class="input_p">联系人姓名:</p>'
+'</div>'
+'<div class="pc_content">'
+'<input type="text" placeholder="请填写">'
+'</div>'
+'</div>'
+'<div class="pc_box" data-field="phone">'
+'<div class="pc_info">'
+'<p class="input_p">联系人手机号:</p>'
+'</div>'
+'<div class="pc_content">'
+'<input type="text" placeholder="请填写">'
+'</div>'
+'</div>'
+'<div class="pc_box" data-field="address">'
+'<div class="pc_info">'
+'<p class="input_p">联系人地址:</p>'
+'</div>'
+'<div class="pc_content">'
+'<input type="text" class="long_input" placeholder="请填写">'
+'</div>'
+'</div>'
+'<div class="pc_box" data-field="fixed_phone">'
+'<div class="pc_info">'
+'<p class="input_p">固定电话:</p>'
+'</div>'
+'<div class="pc_content">'
+'<input type="text" placeholder="请填写">'
+'</div>'
+'</div>'
+'<div class="pc_box" data-field="fax">'
+'<div class="pc_info">'
+'<p class="input_p">联系人传真:</p>'
+'</div>'
+'<div class="pc_content">'
+'<input type="text" placeholder="请填写">'
+'</div>'
+'</div>'
+'<div class="pc_box" data-field="email">'
+'<div class="pc_info">'
+'<p class="input_p">联系人邮箱地址:</p>'
+'</div>'
+'<div class="pc_content">'
+'<input type="text" placeholder="请填写">'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>';